[package]
name = "jlox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"
# TODO: Hack to generate docs, to be removed later
insta = "*"

[dev-dependencies]
insta = "*"
